use_frameworks!

target 'DGObjC_Example' do

# pod 'AFNetworking', :subspecs=>['Reachability']
# pod 'Masonry'


  pod 'DGObjC', :path => '../'
  
  

  target 'DGObjC_Tests' do
    inherit! :search_paths

    
  end
end
