use_frameworks!

target 'DGObjC_Example' do
  pod 'DGObjC', :path => '../'
  
  
  #第三方
  pod 'Masonry'
#  pod 'AFNetworking'
  pod 'AFNetworking/Reachability'
  
  target 'DGObjC_Tests' do
    inherit! :search_paths

    
  end
end
